"""Database package for OnCallPilot."""

from oncallpilot_api.db.models import (
    Base,
    ChatMessage,
    ChatSession,
    DATASOURCE_HEALTH_STATUSES,
    DatasourceStatus,
    INCIDENT_STATUSES,
    Incident,
    IncidentMemory,
    InvestigationSession,
    RemediationAction,
    RunbookDocument,
    ServiceCatalogEntry,
    TOOL_CALL_STATUSES,
    ToolCall,
)
from oncallpilot_api.db.repositories import (
    append_chat_message,
    append_tool_call,
    create_chat_session,
    create_incident_with_fingerprint_dedup,
    create_investigation_session,
    get_all_datasource_statuses,
    get_investigation_detail,
    list_recent_incidents,
    mark_incident_resolved,
    upsert_datasource_status,
)
from oncallpilot_api.db.session import get_db_session

__all__ = [
    "Base",
    "ChatMessage",
    "ChatSession",
    "DATASOURCE_HEALTH_STATUSES",
    "DatasourceStatus",
    "INCIDENT_STATUSES",
    "Incident",
    "IncidentMemory",
    "InvestigationSession",
    "RemediationAction",
    "RunbookDocument",
    "ServiceCatalogEntry",
    "TOOL_CALL_STATUSES",
    "ToolCall",
    "append_chat_message",
    "append_tool_call",
    "create_chat_session",
    "create_incident_with_fingerprint_dedup",
    "create_investigation_session",
    "get_all_datasource_statuses",
    "get_db_session",
    "get_investigation_detail",
    "list_recent_incidents",
    "mark_incident_resolved",
    "upsert_datasource_status",
]
